-- Find the total revenue generated by each category

SELECT 
	c.categoryName, 
	SUM(od.quantity * od.unitPrice * (1-od.discount)) AS TotalRevenue
FROM [Northwind Trade Food Sales].dbo.order_details od
JOIN [Northwind Trade Food Sales].dbo.products p
ON od.productID = p.productID
JOIN [Northwind Trade Food Sales].dbo.categories c
ON p.categoryID = c.categoryID
GROUP BY c.categoryName
ORDER BY TotalRevenue DESC;