-- Total revenue generated by each customer

SELECT cust.customer_id,
	CONCAT(cust.first_name,' ',cust.last_name) AS Customer,
    SUM(p.amount) AS Payment
FROM customer cust
INNER JOIN rental r 
ON cust.customer_id = r.customer_id 
INNER JOIN payment p 
ON r.rental_id = p.rental_id
GROUP BY cust.customer_id
ORDER BY Payment DESC;
